name: yet_another_note_app
description: "A Yeat Another Note App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/background.svg
    - assets/images/logo.svg
  fonts:
    - family: CustomIcon
      fonts:
        - asset : assets/fonts/yana-fonts.ttf

  uses-material-design: true

# flutter:
  
